version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "createBookImage"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-n9c3u37j1kv1"
s3_prefix = "createBookImage"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
